### ISSUE TITLE
Descriptions

### ISSUE THREAD

**Issue by m1guelpf** [aniftyco/awesome-tailwindcss#104]
See https://github.com/aniftyco/awesome-tailwindcss/pull/103#issuecomment-438851673

**Comment by joshmanders** [comment]
I'd like to see more information than just titles, so +1 for descriptions here.

**Comment by m1guelpf** [comment]
Should we enforce it? If so, should we add descriptions for already-included items? What format are we choosing? What about personal pages, how do we describe them?

**Comment by joshmanders** [comment]
I'd say all links need descriptions, in this format

```
[Josh Manders](https://joshmanders.com) - Thoughts, Stories & Ideas. The personal website of Josh Manders.
```

Basically give some information about what the link is outside of just the name.

We'll have to go through and add descriptions for existing links, and make sure contributing guide has information letting people know of this.

**Comment by hawezo** [comment]
#183 added descriptions and guidelines for them, so we can close this. 👍
