### ISSUE TITLE
CMS with Tailwind 1.0?

### ISSUE THREAD

**Issue by jacobpatton** [aniftyco/awesome-tailwindcss#142]
I love this project -- it's so helpful!

Does anyone know of a boilerplate CMS that's ready to run with Tailwind v1? I've already looked at some of the other offerings, and they don't yet support the 1.0 release.

**Comment by Log1x** [comment]
Not a CMS per-say but https://nova.laravel.com/ uses Tailwind on the backend and is in-progress of getting updated to v1.0 (by the looks of things, it should be rather soon)

**Comment by virkillz** [comment]
You can just upgrade it to v1. I made CLI tool to convert html with Tailwind class name to be v1 compatible. https://www.npmjs.com/package/tailupgrade

**Comment by joshmanders** [comment]
Tailwind has an official [discussions](https://github.com/tailwindcss/discuss) repo and [discord](https://tailwindcss.com/discord) now, so I'm gonna close this issue.
