### ISSUE TITLE
Clean up repo and get ready for inclusion in Awesome.

### ISSUE THREAD

**Issue by joshmanders** [aniftyco/awesome-tailwindcss#93]
Hey everyone, Sindre and some others have reviewed the PR for including `awesome-tailwindcss` into `awesome` and there needs to be some fixes and cleanups.

I'm pretty busy and haven't had much time to get to it, so I'm asking for assistance from the community.

You can read the PR here for more information. https://github.com/sindresorhus/awesome/pull/1154#pullrequestreview-143387275

**Comment by m1guelpf** [comment]
Here's a checklist:

- [ ] Consistent and correct naming. You use Tailwindcss and TailwindCSS (without space). You just need to capitalize on CSS and add spaces.

- [ ] Entries should have a description unless the title is descriptive enough by itself.

- [ ] If you use public domain license it would be better to include also this sentence "To the extent possible under law, @joshmanders has waived all copyright and related or neighboring rights to this work."

**Comment by omarkhatibco** [comment]
I added a PR to fixing Linter errors #94

**Comment by carbontwelve** [comment]
I added a PR (#95) that should deal with tasks one and three that @m1guelpf raised.

**Comment by joshmanders** [comment]
Thanks for the fixes! Just need to get descriptions and I think we'll be ready to go on this.

**Comment by m1guelpf** [comment]
@joshmanders How about a bot to autodetect issues with new PRs?

**Comment by joshmanders** [comment]
@m1guelpf yeah I was thinking the same thing. Have any suggestions?

Also want to get it setup on travis for linting and possible have a bot setup so that as long as linting and everything passes, it waits for one of us to just approve the PR and it'll merge it for us.

**Comment by joshmanders** [comment]
Fixed in https://github.com/aniftyco/awesome-tailwindcss/pull/183
